// Registrer the attributes on all blocks...
// Provide a function to get the copilot attributes for a given block...
// Provide a function to set the copilot attributes (feature, tokensUsed, userId) for a given block...
